version: '3.7'

networks:
  default:
    driver: bridge
  traefik-net:
    name: traefik_net
    external: true

volumes:
  mysqldata: {}

services:
  web:
    image: nginx:latest
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT}-web.rule=Host(`${PROJECT_HOST}`)"
      - "traefik.http.routers.${PROJECT}-web.entrypoints=web"
      - "traefik.docker.network=traefik_net"
    networks:
      - default
      - traefik-net

  php:
    build:
      context: ./docker/php-fpm
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - default
      - traefik-net
    labels:
      - "traefik.enable=false"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    networks:
      - default
    labels:
      - "traefik.enable=false"

  phpmyadmin:
    image: phpmyadmin:5.2
    links:
      - mysql
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
      PMA_ARBITRARY: 1
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASS}
      PMA_ABSOLUTE_URI: "http://${PHP_MYADMIN_HOST}/"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.routers.${PROJECT}-phpmyadmin.rule=Host(`${PHP_MYADMIN_HOST}`)"
      - "traefik.http.routers.${PROJECT}-phpmyadmin.entrypoints=web"
    networks:
      - default
      - traefik-net
